---
title: "Process startle probability"
format: html
---

```{r}
library(tidyverse)
library(here)
```

Extra processing scripts
```{r}
source(here('R', 'read_pps_file.R'))
```

Location of the data.
```{r}
# data downloaded into the current working directory
datadir <- here('Processed data')

# could be
# datadir <- "Z:\Hypercapnia\Hypercapnia\2025-07-02"
# on the Windows machine, but then don't use here
```

Find all the .pps files.
```{r}
ppsfiles <- list.files(datadir, pattern = '.*\\.pps',
                       full.names = TRUE, recursive = TRUE)

if (length(ppsfiles) == 0) {
  cli::cli_alert_danger("Didn't find any .pps files in {datadir}!")
} else {
  cli::cli_alert_success("Found {length(ppsfiles)} data files!")
}
```

```{r}
data <- map(ppsfiles, read_pps_file) |> 
  bind_rows()
```

```{r}
data
```

Process the filename to get the trial and rep number.
```{r}
trialrep = str_match(data$cinefile, 'Trial(?<trial>\\d+)-(?<rep>\\d+)')
data <- data |> 
  mutate(trial = trialrep[,2],
         rep = trialrep[,3])
```

```{r}
head(data)
```

This takes the X and Y coordinates and pivots the dataset into "long" format,
where the X and Y number is stored under "indiv", and all the X and Y coordinates
are under just one X and Y column.
```{r}
datalong <-
  data |> pivot_longer(cols = c(starts_with('X'), starts_with('Y')),
                     names_pattern = '(.)(.)\\.mm',
                     names_to = c('.value', 'indiv')) |> 
  filter(!is.na(X))

head(datalong)
```

```{r}
cumuldata <-
  datalong |> 
  group_by(trial, rep, frame) |> 
  summarize(nstartle = n(),
            timefromtrig.s = first(timefromtrig.s)) |> 
  group_by(trial, rep) |> 
  mutate(totalstartle = cumsum(nstartle))

head(cumuldata)
```

```{r}
cumuldata |> 
  ggplot(aes(x = timefromtrig.s, y = totalstartle, color = rep)) +
  geom_step() +
  facet_wrap(~ rep)
```



